services:
  web:
    build: .
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ../:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    restart: always
    volumes:
      -db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Afpa1234
      MYSQL_DATABASE: Thedistrict
      MYSQL_USER: admin

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025